In [1]:
import pandas as pd

In [2]:
TRAIN_DATA_PATH = './Results/Selected_Data/RS42_preselected_n3_preselected_False_train_data.parquet'
TEST_DATA_PATH  = './Results/Selected_Data/RS42_preselected_n3_preselected_False_test_data.parquet'

In [3]:
df_train = pd.read_parquet(TRAIN_DATA_PATH)
df_test = pd.read_parquet(TEST_DATA_PATH)

In [4]:
df_train

,CircuS_r1-3_c(c)c(cc)[C@@H]1O[C@H]1C(=O)C,CircuS_r1-3_ccc,Sterimol_Beta_R1_B5,ee
index,,,,
59,1,11,9.582010,97
28,1,9,7.630167,85
0,1,9,6.934047,92
62,1,5,5.814947,0
34,0,5,4.134226,79
48,0,5,5.644025,0
7,0,9,5.675129,18
41,0,9,5.811075,0
30,1,9,7.720555,78
54,0,5,5.838340,0
19,1,7,5.823108,96
44,0,7,5.385045,0
42,1,9,7.797325,0
31,1,7,5.820190,94
46,0,5,4.532660,0
13,0,12,5.867556,52
53,0,10,5.492625,0
3,1,10,5.818045,97
17,1,5,5.813767,95
33,0,5,5.378819,90
8,1,9,7.260119,95
47,1,5,5.813877,0
6,1,9,6.625616,85
66,0,0,13.834645,0
65,1,7,5.819923,0
15,0,9,5.681206,53
27,1,9,5.815033,93
26,0,5,5.507089,98
24,1,8,7.012005,94
50,0,6,7.084796,0
11,0,0,5.265682,35
32,1,12,5.804186,77
63,0,4,7.608073,0
49,0,6,7.025918,0
37,0,10,4.921748,18
29,1,8,6.392895,90
43,0,7,5.356508,0
55,0,10,5.737716,0
1,0,9,5.758544,55
21,1,10,5.825119,98
2,1,9,7.011927,97
56,0,5,5.748330,0
39,0,0,4.515884,0
35,1,8,7.004169,52
52,0,5,5.682456,0
23,1,12,5.817976,91
58,1,9,8.372047,97
10,1,9,5.818032,92
22,1,9,7.578548,94
18,0,10,7.672087,97
57,1,14,10.388757,97
38,0,0,5.161439,70
20,1,10,5.823569,98
60,1,5,5.825866,0
14,1,9,5.818570,92
51,0,5,5.569211,0

In [5]:
df_train.to_excel('final_model_train_data.xlsx')

In [6]:
df_test

,CircuS_r1-3_c(c)c(cc)[C@@H]1O[C@H]1C(=O)C,CircuS_r1-3_ccc,Sterimol_Beta_R1_B5,ee
index,,,,
36,1,8,7.012573,81
16,1,7,5.822345,93
4,0,9,5.730263,74
9,0,0,3.252607,45
45,0,7,5.433542,0
40,0,9,5.862721,0
61,1,4,7.598097,0
5,1,9,7.313662,79
64,0,4,7.258730,0
12,1,12,7.610381,96
25,0,10,7.768271,99

In [7]:
df_test.to_excel('final_model_test_data.xlsx')