In [1]:
import pandas as pd

In [2]:
TRAIN_DATA_PATH = './Results/Selected_Data/RS42_consensus_n7_fast_aggr_False_train_data.parquet'
TEST_DATA_PATH  = './Results/Selected_Data/RS42_consensus_n7_fast_aggr_False_test_data.parquet'

In [3]:
df_train = pd.read_parquet(TRAIN_DATA_PATH)
df_test = pd.read_parquet(TEST_DATA_PATH)

In [4]:
df_train

,IC1,GATS6are,ATSC1c,CIC1,GATS4d,PEOE_VSA6,SMR_VSA6,ee
index,,,,,,,,
10,2.215431,1.450107,-0.084316,3.428425,1.105442,109.204260,0.000000,95.0
40,2.586296,1.152795,-0.324279,2.968293,1.137595,78.872425,7.109798,3.0
46,2.210029,1.953335,-0.081006,3.249403,0.990963,97.071526,0.000000,95.0
2,2.604792,2.170641,-0.092202,2.821472,0.514117,87.510902,0.000000,95.0
48,3.431606,1.158548,-0.215509,2.375749,0.860235,52.337799,19.972449,36.0
20,2.516244,1.996655,-0.082020,2.693209,1.052031,73.663428,5.752854,91.0
26,2.720583,1.293825,-0.178036,2.527345,1.010057,66.739691,12.359736,12.0
12,2.602357,1.607074,-0.269045,2.952232,1.084997,84.938792,0.000000,92.0
6,2.499065,1.942229,-0.080116,3.055524,0.880022,96.568611,0.000000,97.5
37,2.835719,1.152763,-0.271555,2.373735,0.960853,60.663671,0.000000,26.0
8,2.459432,1.915680,-0.091616,3.000000,0.917373,90.473365,0.000000,91.0
33,2.601007,1.475518,-0.080702,2.756545,1.050168,78.891731,0.000000,70.0
7,2.634762,1.452270,-0.170629,2.950201,0.924388,78.872425,7.109798,97.0
17,2.459432,2.017458,-0.091830,3.000000,0.917373,90.473365,0.000000,97.0
34,2.890365,1.696440,-0.084158,2.633197,1.011461,86.505071,0.000000,48.0
38,2.921833,0.927036,-0.334498,2.504432,1.155689,60.663671,6.606882,15.0
35,2.828083,2.358330,-0.082559,2.815773,0.930447,86.002156,0.000000,59.0
32,2.470041,1.536930,-0.098839,3.084548,1.079800,78.862772,0.000000,77.0
25,3.108597,0.961396,-0.604095,2.646291,1.015725,66.739691,12.297610,32.0
49,3.402159,1.335711,-0.108016,2.430732,0.846658,52.337799,17.258561,74.0
14,2.685772,1.421236,-0.089206,3.121583,0.728277,111.776371,0.000000,99.0
22,2.624749,2.164047,-0.083183,2.929840,0.856911,86.002156,0.000000,94.0
24,3.041999,1.234626,-0.304114,2.601857,0.858552,66.739691,12.862651,97.0
1,2.981252,0.187981,-0.071224,1.972944,0.878262,36.407855,0.000000,46.0
3,2.958623,0.199112,-0.071595,2.128839,1.058491,36.407855,0.000000,50.0
43,2.356497,1.705328,-0.228855,3.069767,0.912919,78.872425,5.733667,74.0
15,2.459432,1.826115,-0.090874,3.000000,0.984826,96.539732,0.000000,92.0
28,2.499065,1.560923,-0.080687,3.055524,0.963267,91.005159,0.000000,72.0
53,3.292515,1.128214,-0.310535,2.462372,0.900952,64.992755,12.862651,60.0
58,2.757347,1.093294,-0.222431,3.308743,0.783337,111.776371,0.000000,72.5
60,2.499065,1.764639,-0.080409,3.055524,0.975160,91.005159,0.000000,98.0
30,2.459432,1.562847,-0.090779,3.000000,0.971336,90.463712,0.000000,87.0
61,2.653997,1.516895,-0.085387,2.869565,1.036497,72.796405,0.000000,46.0
23,2.875321,0.855415,-0.301266,2.550944,0.962687,66.739691,12.862651,88.0
21,2.468377,2.038293,-0.088293,2.779550,0.976389,72.815711,5.752854,92.0
47,3.167652,1.051658,-0.269785,2.690329,0.838824,66.739691,12.359736,27.0
9,2.602357,0.794562,-0.274399,2.952232,0.847059,78.872425,0.000000,93.0
36,2.830476,3.930824,-0.089881,2.693086,0.693651,87.510902,0.000000,77.0
44,2.780710,0.931286,-0.305205,2.541219,0.916467,66.739691,12.862651,43.0
0,1.919168,2.105603,-0.082204,3.438384,0.993859,84.938792,0.000000,80.0
16,2.653997,1.510502,-0.086419,2.869565,1.140147,84.938792,0.000000,93.0
45,2.966464,1.208577,-0.276867,2.492968,1.039816,66.739691,12.297610,0.0
51,3.330809,1.172368,-0.570589,2.527172,1.020972,42.474223,19.972449,0.0
57,3.208576,1.051397,-0.309585,2.183741,0.992071,42.464569,12.862651,10.0
5,2.384935,1.709827,-0.077968,3.169654,1.041292,97.071526,5.752854,92.0
39,2.653997,1.277902,-0.090191,2.869565,0.875264,78.872425,0.000000,80.0
54,2.840102,0.839934,-0.084083,2.481826,1.218750,66.739691,0.000000,58.0
50,3.228703,1.693060,-0.094784,2.386007,0.744982,64.992755,5.752854,52.0
55,2.153455,1.866131,-0.078378,3.601432,1.219880,121.327341,0.000000,80.0
4,2.997072,0.099556,-0.067549,2.090391,0.977352,35.904940,0.000000,82.0
62,3.421826,0.958117,-0.323767,2.532371,0.967697,52.337799,24.368358,22.0
19,2.530568,1.315944,-0.170239,2.826984,1.006910,66.739691,0.000000,98.0
42,2.746685,1.658205,-0.085153,3.034675,1.118257,66.739691,0.000000,6.0

In [5]:
df_train.to_excel('final_model_train_data.xlsx')

In [6]:
df_test

,IC1,GATS6are,ATSC1c,CIC1,GATS4d,PEOE_VSA6,SMR_VSA6,ee
index,,,,,,,,
11,2.215431,1.700711,-0.084079,3.428425,1.009779,103.137893,0.000000,94.0
13,2.138687,1.302255,-0.081634,3.446276,1.042077,109.223566,0.000000,96.0
41,2.719416,1.389052,-0.201783,2.638136,0.824339,66.739691,0.000000,40.0
52,3.392153,1.191591,-0.545758,2.415202,1.005541,52.337799,19.972449,44.0
59,2.926247,0.176270,-0.069788,1.881108,0.631169,36.407855,0.000000,80.0
31,2.579349,1.702707,-0.089432,2.778203,0.975070,66.730038,0.000000,85.0
18,2.602357,0.800758,-0.274570,2.952232,0.847059,78.872425,0.000000,90.0
27,2.653997,1.188641,-0.089328,2.869565,0.875264,66.739691,0.000000,25.0
29,2.634762,0.933649,-0.172214,2.950201,1.121591,78.862772,7.109798,67.0
56,3.182729,1.339199,-0.493244,2.243535,1.065487,54.606957,12.862651,1.5

In [7]:
df_test.to_excel('final_model_test_data.xlsx')