In [1]:
import pandas as pd

In [2]:
TRAIN_DATA_PATH = './Results/Selected_Data/RS42_consensus_n8_cv_safe_False_train_data.parquet'
TEST_DATA_PATH  = './Results/Selected_Data/RS42_consensus_n8_cv_safe_False_test_data.parquet'

In [3]:
df_train = pd.read_parquet(TRAIN_DATA_PATH)
df_test = pd.read_parquet(TEST_DATA_PATH)

In [4]:
df_train

,ATS5s,ATS3i,AMID_C,AATSC4i,nRot,Sterimol_Beta_R1_B5,ATSC7Z,GATS3d,ee
index,,,,,,,,,
18,143.709877,9593.672406,1.859402,-0.146162,3,5.704055,-105.507804,1.057147,98
20,178.333333,11144.866298,1.973651,-0.150667,3,5.665747,-60.000000,1.186483,91
30,200.111111,10241.117233,1.638444,-0.116371,4,6.742263,9.256198,1.119675,52
12,143.666667,8968.874127,1.807555,-0.033085,3,5.664834,-41.887755,1.138455,92
31,187.802469,9407.266102,1.550490,-0.088103,4,6.427996,-48.240000,1.125722,81
0,147.000000,9581.225406,1.911027,-0.119915,3,6.725733,-24.963580,1.144794,92
9,40.000000,7586.015714,1.748149,-0.373119,0,5.227330,0.000000,0.926082,35
28,211.444444,11150.333210,1.973748,-0.169095,3,5.661697,-10.000000,1.263862,77
15,96.666667,8852.907059,1.817717,0.109843,3,5.662808,-92.100137,1.109853,95
21,143.358025,8937.511690,1.712613,-0.040997,3,6.640660,-79.030612,1.096082,94
27,149.333333,8885.630410,1.768705,-0.270763,3,5.661935,-2.525565,1.400000,94
17,154.166667,9836.708624,1.859402,-0.056608,3,5.704207,-72.350676,1.057147,98
11,186.555556,11150.333210,1.974210,-0.168458,3,5.641603,39.000000,1.315448,52
1,133.378601,8748.849206,1.806876,-0.104898,3,5.615868,21.500000,1.237451,55
32,211.777778,9397.622782,1.815457,-0.085030,4,4.384168,3.973333,1.243768,18
5,211.777778,9438.628539,1.626890,-0.117700,4,7.355879,-10.240000,1.104789,85
24,222.500000,9839.605848,1.652356,-0.317470,3,7.368483,-63.898023,1.138128,85
2,134.691358,8747.374275,1.807554,-0.102342,3,6.428952,-58.500000,1.138455,97
26,171.111111,9492.667877,1.812061,-0.220812,4,7.402149,45.355469,1.285714,78
19,159.000000,8989.806772,1.820857,-0.128951,3,7.130029,-41.510107,1.166100,94
36,164.333333,9492.667877,1.812123,-0.220072,4,6.836740,-55.417969,1.317460,0
22,148.777778,10014.650918,1.924016,-0.080077,4,6.830812,35.375000,1.217733,99
38,205.277778,12615.223310,1.884771,0.008786,5,7.179728,-26.221565,1.150349,97
39,201.222222,13864.582262,1.917701,0.132818,5,7.325639,26.597500,1.001436,97
25,201.111111,9628.765954,1.550490,-0.049089,4,6.028790,-23.333333,1.125722,90
3,135.000000,8778.736711,1.914363,-0.090642,3,5.664358,-29.193878,1.198573,97
35,176.277778,9492.622033,1.811841,-0.175939,4,5.629769,45.792969,1.428571,0
8,144.666667,9581.225406,1.910988,-0.119915,3,5.664363,-83.899063,1.144794,92
16,137.820988,9593.690058,1.859580,-0.145701,3,7.754393,1.976067,1.158518,97
4,190.333333,9438.628539,1.627004,-0.081239,4,7.224662,-52.240000,1.162181,79
23,177.111111,9586.692318,1.910944,-0.255535,3,5.659803,0.036420,1.373753,93
6,239.555556,9436.440839,1.626491,-0.172332,4,5.639724,28.160000,1.276964,18

In [5]:
df_train.to_excel('final_model_train_data.xlsx')

In [6]:
df_test

,ATS5s,ATS3i,AMID_C,AATSC4i,nRot,Sterimol_Beta_R1_B5,ATSC7Z,GATS3d,ee
index,,,,,,,,,
37,129.333333,8077.610614,1.767820,-0.038282,3,5.511457,-47.000000,1.233819,0
13,190.333333,9038.243554,1.860136,-0.009447,1,5.479057,-75.663265,1.178436,53
7,134.129630,8690.008748,1.807554,-0.125359,3,6.659977,-110.204082,1.138455,95
29,126.333333,8852.640435,1.814888,0.107435,3,4.481087,-74.989026,0.930845,79
14,114.333333,7385.685988,1.768326,-0.095792,3,5.663262,-26.014400,1.201923,93
10,175.777778,11144.866298,1.973998,-0.150667,3,8.051359,3.000000,1.212276,96
33,85.333333,9213.058409,1.697269,-0.023298,5,7.253400,-9.000000,0.829082,70
40,213.388889,11858.797464,1.884473,-0.240183,4,8.705143,0.000000,1.247184,97
34,156.777778,9586.692318,1.910930,-0.254818,3,5.620681,-58.899063,1.373753,0

In [7]:
df_test.to_excel('final_model_test_data.xlsx')