In [1]:
import pandas as pd

In [2]:
TRAIN_DATA_PATH = './Results/Selected_Data/RS42_consensus_n6_fast_aggr_False_train_data.parquet'
TEST_DATA_PATH  = './Results/Selected_Data/RS42_consensus_n6_fast_aggr_False_test_data.parquet'

In [3]:
df_train = pd.read_parquet(TRAIN_DATA_PATH)
df_test = pd.read_parquet(TEST_DATA_PATH)

In [4]:
df_train

,Sterimol_Beta_R2_B5,Sterimol_Alpha_R1_L,CircuS_r1-3_O1[C@@H](C)C1,CircuS_r1-3_ccc,CircuS_r1-3_C[C@@H]1O[C@H]1C(=O)C,CircuS_r1-3_[C@@H]1([C@H](C)O1)C,epox_cla
index,,,,,,,
7,2.070314,3.617450,0,9,0,0,1
14,2.067231,3.616961,2,9,1,1,1
54,2.059671,3.609722,1,5,0,0,0
48,4.286395,3.599733,0,5,0,0,0
22,2.067994,3.617612,2,9,1,1,1
33,2.040956,3.606944,1,5,0,0,1
57,2.067546,3.617168,2,14,1,1,1
27,2.067656,3.616557,2,9,1,1,1
65,2.066949,3.617165,2,7,1,1,0
42,2.067288,3.617235,2,9,1,1,0
10,2.067349,3.616975,2,9,1,1,1
6,2.068325,3.618062,2,9,1,1,1
3,2.067347,3.616975,2,10,1,1,1
41,2.066435,3.619970,2,9,1,1,0
64,2.061142,3.615073,2,4,0,1,0
2,2.067769,3.617434,2,9,1,1,1
16,2.066479,3.616935,2,7,1,1,1
43,2.068037,3.612368,1,7,0,0,0
24,2.067688,3.617435,2,8,1,1,1
56,2.074536,3.616559,1,5,0,0,0
46,4.532660,3.628098,1,5,0,0,0
49,2.065944,3.621464,2,6,1,1,0
13,2.068758,3.621326,2,12,1,1,1
23,2.067296,3.616992,2,12,1,1,1
28,2.067877,3.617422,2,9,1,1,1
36,2.067587,3.617413,2,8,1,1,1
40,2.068315,3.619640,2,9,1,1,0
30,2.068118,3.616714,2,9,1,1,1
59,2.067531,3.617227,2,11,1,1,1
12,2.067374,3.617180,2,12,1,1,1
25,2.064237,3.614906,2,10,1,1,1
4,2.068341,9.078675,1,9,0,0,1
19,2.066228,3.617306,2,7,1,1,1
58,2.067315,3.616935,2,9,1,1,1
61,2.065963,3.617441,2,4,1,1,0
5,2.068166,3.617777,2,9,1,1,1
53,2.085562,3.601800,1,10,0,0,0
55,2.075358,3.616060,1,10,0,0,0
66,2.030306,5.651460,1,0,0,0,0
0,2.067321,3.616927,2,9,1,1,1
38,2.048617,3.609030,2,0,1,1,1
20,2.064491,3.616960,2,10,1,1,1
39,2.036422,4.620577,1,0,0,0,0
37,2.063052,3.611928,2,10,2,1,1
45,2.070168,3.614554,1,7,0,0,0
60,2.065626,3.617441,2,5,1,1,0
29,2.067544,3.617381,2,8,1,1,1
15,2.072617,8.458294,0,9,0,0,1
62,2.067512,3.614471,2,5,1,1,0
52,2.072456,6.072160,0,5,0,0,0
8,2.067712,3.617341,2,9,1,1,1
9,4.531767,3.612228,0,0,0,0,1
50,2.065344,3.621577,2,6,1,1,0
17,2.067426,3.614334,2,5,1,1,1
18,2.063026,3.612527,2,10,1,1,1
35,2.067101,3.616907,2,8,1,1,1

In [6]:
df_train.to_excel('final_model_train_data.xlsx')

In [5]:
df_test

,Sterimol_Beta_R2_B5,Sterimol_Alpha_R1_L,CircuS_r1-3_O1[C@@H](C)C1,CircuS_r1-3_ccc,CircuS_r1-3_C[C@@H]1O[C@H]1C(=O)C,CircuS_r1-3_[C@@H]1([C@H](C)O1)C,epox_cla
index,,,,,,,
1,2.069732,3.616699,0,9,0,0,1
31,2.065959,3.616981,2,7,1,1,1
26,2.063133,3.614390,2,5,1,1,1
51,2.077087,6.481032,0,5,0,0,0
44,2.061182,3.613506,2,7,1,1,0
32,2.053431,3.618200,2,12,1,1,1
21,2.065017,3.618622,2,10,1,1,1
11,2.052098,3.610307,1,0,0,0,1
47,2.067440,3.614784,2,5,1,1,0
34,2.043100,3.615890,2,5,1,1,1
63,2.061008,3.614780,2,4,0,1,0

In [7]:
df_test.to_excel('final_model_test_data.xlsx')